// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for About documents */
interface AboutDocumentData {
  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismicT.KeyTextField;
  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismicT.KeyTextField;
  /**
   * Meta Author field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_author: prismicT.KeyTextField;
  /**
   * Meta Keywords field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_keywords: prismicT.KeyTextField;
  /**
   * Meta Robots field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_robots: prismicT.KeyTextField;
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<AboutDocumentDataSlicesSlice>;
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices1[]
   * - **Tab**: Page Content
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices1: prismicT.SliceZone<AboutDocumentDataSlices1Slice>;
}
/**
 * Slice for *About → Slice Zone*
 *
 */
type AboutDocumentDataSlicesSlice = never;
/**
 * Slice for *About → Slice Zone*
 *
 */
type AboutDocumentDataSlices1Slice = FragmentSlice;
/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;
/** Content for Blog documents */
interface BlogDocumentData {
  /**
   * Name field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.name
   * - **Tab**: Page Content
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismicT.KeyTextField;
  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismicT.KeyTextField;
  /**
   * Meta Author field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_author: prismicT.KeyTextField;
  /**
   * Meta Keywords field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_keywords: prismicT.KeyTextField;
  /**
   * Meta Robots field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_robots: prismicT.KeyTextField;
}
/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;
/** Content for BlogPost documents */
interface BlogpostDocumentData {
  /**
   * Name field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.name
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Header field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.header
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  header: prismicT.KeyTextField;
  /**
   * DateCreated field in *BlogPost*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.datecreated
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
   *
   */
  datecreated: prismicT.TimestampField;
  /**
   * Slice Zone field in *BlogPost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.slices[]
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<BlogpostDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismicT.KeyTextField;
  /**
   * Meta Description field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismicT.KeyTextField;
  /**
   * Meta Author field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_author: prismicT.KeyTextField;
  /**
   * Meta Keywords field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_keywords: prismicT.KeyTextField;
  /**
   * Meta Robots field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_robots: prismicT.KeyTextField;
}
/**
 * Slice for *BlogPost → Slice Zone*
 *
 */
type BlogpostDocumentDataSlicesSlice = BlogPostContentSlice;
/**
 * BlogPost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;
/** Content for Contact documents */
interface ContactDocumentData {
  /**
   * Header field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.header
   * - **Tab**: Page Content
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  header: prismicT.KeyTextField;
  /**
   * Subheading field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.subheading
   * - **Tab**: Page Content
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subheading: prismicT.KeyTextField;
  /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismicT.KeyTextField;
  /**
   * Meta Author field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_author: prismicT.KeyTextField;
  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismicT.KeyTextField;
  /**
   * Meta Keywords field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_keywords: prismicT.KeyTextField;
  /**
   * Meta Robots field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_robots: prismicT.KeyTextField;
}
/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;
/** Content for CookieBar documents */
interface CookiebarDocumentData {
  /**
   * Name field in *CookieBar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookiebar.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * DeclineButtonText field in *CookieBar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookiebar.declinebuttontext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  declinebuttontext: prismicT.KeyTextField;
  /**
   * AcceptButtonText field in *CookieBar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookiebar.acceptbuttontext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  acceptbuttontext: prismicT.KeyTextField;
  /**
   * Content field in *CookieBar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookiebar.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  content: prismicT.KeyTextField;
  /**
   * ExpirationTimeInDays field in *CookieBar*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cookiebar.expirationtimeindays
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  expirationtimeindays: prismicT.NumberField;
}
/**
 * CookieBar document from Prismic
 *
 * - **API ID**: `cookiebar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CookiebarDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<CookiebarDocumentData>,
    "cookiebar",
    Lang
  >;
/** Content for Footer documents */
interface FooterDocumentData {
  /**
   * Copy field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  copy: prismicT.RichTextField;
  /**
   * logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<"desktop">;
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<FooterDocumentDataSlicesSlice>;
}
/**
 * Slice for *Footer → Slice Zone*
 *
 */
type FooterDocumentDataSlicesSlice = LinkIconSlice;
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Form documents */
interface FormDocumentData {
  /**
   * Name field in *Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * SubmitLabel field in *Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.submitlabel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  submitlabel: prismicT.KeyTextField;
  /**
   * Slice Zone field in *Form*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: form.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<FormDocumentDataSlicesSlice>;
}
/**
 * Slice for *Form → Slice Zone*
 *
 */
type FormDocumentDataSlicesSlice = TextInputSlice;
/**
 * Form document from Prismic
 *
 * - **API ID**: `form`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<FormDocumentData>, "form", Lang>;
/** Content for FormGroup documents */
interface FormgroupDocumentData {
  /**
   * Name field in *FormGroup*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formgroup.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Slice Zone field in *FormGroup*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: formgroup.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<FormgroupDocumentDataSlicesSlice>;
}
/**
 * Slice for *FormGroup → Slice Zone*
 *
 */
type FormgroupDocumentDataSlicesSlice = TextInputSlice;
/**
 * FormGroup document from Prismic
 *
 * - **API ID**: `formgroup`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormgroupDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<FormgroupDocumentData>,
    "formgroup",
    Lang
  >;
/** Content for Header documents */
interface HeaderDocumentData {
  /**
   * header field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  header: prismicT.KeyTextField;
  /**
   * subheader field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.subheader
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subheader: prismicT.KeyTextField;
}
/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;
/** Content for Home Page Article documents */
interface HomePageArticleDocumentData {
  /**
   * Name field in *Home Page Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_article.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Header field in *Home Page Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_article.header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  header: prismicT.KeyTextField;
  /**
   * Placement field in *Home Page Article*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_article.placement
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  placement: prismicT.SelectField<"start" | "center" | "end">;
  /**
   * With Intersection field in *Home Page Article*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home_page_article.with_intersection
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  with_intersection: prismicT.BooleanField;
  /**
   * Order field in *Home Page Article*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_article.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  order: prismicT.NumberField;
  /**
   * Slice Zone field in *Home Page Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<HomePageArticleDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home Page Article → Slice Zone*
 *
 */
type HomePageArticleDocumentDataSlicesSlice =
  | PlaceableContentSlice
  | LinkButtonSlice;
/**
 * Home Page Article document from Prismic
 *
 * - **API ID**: `home_page_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageArticleDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<HomePageArticleDocumentData>,
    "home_page_article",
    Lang
  >;
/** Content for Homepage documents */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Page Content
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismicT.KeyTextField;
  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismicT.KeyTextField;
  /**
   * Meta Author field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_author: prismicT.KeyTextField;
  /**
   * Meta Keywords field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_keywords: prismicT.KeyTextField;
  /**
   * Meta Robots field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_robots: prismicT.KeyTextField;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = FragmentSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
/** Content for Navigation documents */
interface NavigationDocumentData {
  /**
   * Name field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismicT.RichTextField;
  /**
   * homePageUrl field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.homepageurl
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  homepageurl: prismicT.LinkField;
  /**
   * homePageIcon field in *Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.homepageicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  homepageicon: prismicT.ImageField<never>;
  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice = NavigationItemSlice;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;
export type AllDocumentTypes =
  | AboutDocument
  | BlogDocument
  | BlogpostDocument
  | ContactDocument
  | CookiebarDocument
  | FooterDocument
  | FormDocument
  | FormgroupDocument
  | HeaderDocument
  | HomePageArticleDocument
  | HomepageDocument
  | NavigationDocument;
/**
 * Item in BlogPostContent → Items
 *
 */
export interface BlogPostContentSliceDefaultItem {
  /**
   * Content field in *BlogPostContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_content.items[].content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismicT.RichTextField;
  /**
   * Image field in *BlogPostContent → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_content.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Default variation for BlogPostContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BlogPostContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogPostContentSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<BlogPostContentSliceDefaultItem>
>;
/**
 * Slice variation for *BlogPostContent*
 *
 */
type BlogPostContentSliceVariation = BlogPostContentSliceDefault;
/**
 * BlogPostContent Shared Slice
 *
 * - **API ID**: `blog_post_content`
 * - **Description**: `BlogPostContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogPostContentSlice = prismicT.SharedSlice<
  "blog_post_content",
  BlogPostContentSliceVariation
>;
/**
 * Primary content in Fragment → Primary
 *
 */
interface FragmentSliceDefaultPrimary {
  /**
   * Header field in *Fragment → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.primary.header
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  header: prismicT.TitleField;
}
/**
 * Item in Fragment → Items
 *
 */
export interface FragmentSliceDefaultItem {
  /**
   * Content field in *Fragment → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.items[].content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismicT.RichTextField;
}
/**
 * Default variation for Fragment Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Fragment`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FragmentSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<FragmentSliceDefaultPrimary>,
  Simplify<FragmentSliceDefaultItem>
>;
/**
 * Primary content in Fragment → Primary
 *
 */
interface FragmentSliceHomepageFragmentPrimary {
  /**
   * Header field in *Fragment → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.primary.header
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  header: prismicT.TitleField;
  /**
   * Placement field in *Fragment → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.primary.placement
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  placement: prismicT.SelectField<"Left" | "Right">;
  /**
   * With Intersection field in *Fragment → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: fragment.primary.with_intersection
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  with_intersection: prismicT.BooleanField;
}
/**
 * Item in Fragment → Items
 *
 */
export interface FragmentSliceHomepageFragmentItem {
  /**
   * Content field in *Fragment → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.items[].content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismicT.RichTextField;
  /**
   * Button Link field in *Fragment → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.items[].button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismicT.LinkField;
}
/**
 * Homepage Fragment variation for Fragment Slice
 *
 * - **API ID**: `homepageFragment`
 * - **Description**: `Fragment`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FragmentSliceHomepageFragment = prismicT.SharedSliceVariation<
  "homepageFragment",
  Simplify<FragmentSliceHomepageFragmentPrimary>,
  Simplify<FragmentSliceHomepageFragmentItem>
>;
/**
 * Primary content in Fragment → Primary
 *
 */
interface FragmentSliceAboutMeFragmentPrimary {
  /**
   * Header field in *Fragment → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.primary.header
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  header: prismicT.TitleField;
  /**
   * Portrait field in *Fragment → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.primary.portrait
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  portrait: prismicT.ImageField<"tablet" | "desktop">;
}
/**
 * Item in Fragment → Items
 *
 */
export interface FragmentSliceAboutMeFragmentItem {
  /**
   * Content field in *Fragment → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.items[].content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismicT.RichTextField;
}
/**
 * About Me Fragment variation for Fragment Slice
 *
 * - **API ID**: `aboutMeFragment`
 * - **Description**: `Fragment`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FragmentSliceAboutMeFragment = prismicT.SharedSliceVariation<
  "aboutMeFragment",
  Simplify<FragmentSliceAboutMeFragmentPrimary>,
  Simplify<FragmentSliceAboutMeFragmentItem>
>;
/**
 * Slice variation for *Fragment*
 *
 */
type FragmentSliceVariation =
  | FragmentSliceDefault
  | FragmentSliceHomepageFragment
  | FragmentSliceAboutMeFragment;
/**
 * Fragment Shared Slice
 *
 * - **API ID**: `fragment`
 * - **Description**: `Fragment`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FragmentSlice = prismicT.SharedSlice<
  "fragment",
  FragmentSliceVariation
>;
/**
 * Primary content in LinkButton → Primary
 *
 */
interface LinkButtonSliceDefaultPrimary {
  /**
   * Label field in *LinkButton → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_button.primary.label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField;
  /**
   * Href field in *LinkButton → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_button.primary.href
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  href: prismicT.LinkField;
  /**
   * Placement field in *LinkButton → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: link_button.primary.placement
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  placement: prismicT.SelectField<"start" | "center" | "end">;
  /**
   * Disabled field in *LinkButton → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: link_button.primary.disabled
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  disabled: prismicT.BooleanField;
}
/**
 * Default variation for LinkButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: `LinkButton`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LinkButtonSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<LinkButtonSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *LinkButton*
 *
 */
type LinkButtonSliceVariation = LinkButtonSliceDefault;
/**
 * LinkButton Shared Slice
 *
 * - **API ID**: `link_button`
 * - **Description**: `LinkButton`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LinkButtonSlice = prismicT.SharedSlice<
  "link_button",
  LinkButtonSliceVariation
>;
/**
 * Primary content in LinkIcon → Primary
 *
 */
interface LinkIconSliceDefaultPrimary {
  /**
   * Href field in *LinkIcon → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_icon.primary.href
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  href: prismicT.LinkField;
  /**
   * Icon field in *LinkIcon → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: link_icon.primary.icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismicT.ImageField<never>;
}
/**
 * Default variation for LinkIcon Slice
 *
 * - **API ID**: `default`
 * - **Description**: `LinkIcon`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LinkIconSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<LinkIconSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *LinkIcon*
 *
 */
type LinkIconSliceVariation = LinkIconSliceDefault;
/**
 * LinkIcon Shared Slice
 *
 * - **API ID**: `link_icon`
 * - **Description**: `LinkIcon`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LinkIconSlice = prismicT.SharedSlice<
  "link_icon",
  LinkIconSliceVariation
>;
/**
 * Primary content in NavigationItem → Primary
 *
 */
interface NavigationItemSliceDefaultPrimary {
  /**
   * Name field in *NavigationItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: navigation_item.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismicT.RichTextField;
  /**
   * Link field in *NavigationItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismicT.LinkField;
}
/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `NavigationItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *NavigationItem*
 *
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;
/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: `NavigationItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSlice = prismicT.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;
/**
 * Item in PlaceableContent → Items
 *
 */
export interface PlaceableContentSliceDefaultItem {
  /**
   * Content field in *PlaceableContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: placeable_content.items[].content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismicT.RichTextField;
  /**
   * Content Placement field in *PlaceableContent → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: placeable_content.items[].content_placement
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  content_placement: prismicT.SelectField<"start" | "center" | "end">;
  /**
   * Button Link Href field in *PlaceableContent → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: placeable_content.items[].button_link_href
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link_href: prismicT.LinkField;
  /**
   * Button Link Label field in *PlaceableContent → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: placeable_content.items[].button_link_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_link_label: prismicT.KeyTextField;
  /**
   * Button Link Placement field in *PlaceableContent → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: placeable_content.items[].button_link_placement
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  button_link_placement: prismicT.SelectField<"start" | "center" | "end">;
}
/**
 * Default variation for PlaceableContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `PlaceableContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PlaceableContentSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<PlaceableContentSliceDefaultItem>
>;
/**
 * Slice variation for *PlaceableContent*
 *
 */
type PlaceableContentSliceVariation = PlaceableContentSliceDefault;
/**
 * PlaceableContent Shared Slice
 *
 * - **API ID**: `placeable_content`
 * - **Description**: `PlaceableContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PlaceableContentSlice = prismicT.SharedSlice<
  "placeable_content",
  PlaceableContentSliceVariation
>;
/**
 * Primary content in Input → Primary
 *
 */
interface TextInputSliceDefaultPrimary {
  /**
   * Name field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Label field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField;
  /**
   * Placeholder field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  placeholder: prismicT.KeyTextField;
  /**
   * Required field in *Input → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_input.primary.required
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  required: prismicT.BooleanField;
  /**
   * RequiredValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.requiredvalidationmessage
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  requiredvalidationmessage: prismicT.KeyTextField;
  /**
   * MinLength field in *Input → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.minlength
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  minlength: prismicT.NumberField;
  /**
   * MinLengthValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.minlengthvalidationmessage
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  minlengthvalidationmessage: prismicT.KeyTextField;
  /**
   * MaxLength field in *Input → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.maxlength
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  maxlength: prismicT.NumberField;
  /**
   * MaxLengthValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.maxlengthvalidationmessage
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  maxlengthvalidationmessage: prismicT.KeyTextField;
}
/**
 * Default variation for Input Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextInput`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextInputSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<TextInputSliceDefaultPrimary>,
  never
>;
/**
 * Primary content in Input → Primary
 *
 */
interface TextInputSliceTextAreaPrimary {
  /**
   * Name field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Label field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField;
  /**
   * Placeholder field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  placeholder: prismicT.KeyTextField;
  /**
   * Required field in *Input → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_input.primary.required
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  required: prismicT.BooleanField;
  /**
   * RequiredValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.requiredvalidationmessage
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  requiredvalidationmessage: prismicT.KeyTextField;
  /**
   * MinLength field in *Input → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.minlength
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  minlength: prismicT.NumberField;
  /**
   * MinLengthValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.minlengthvalidationmessage
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  minlengthvalidationmessage: prismicT.KeyTextField;
  /**
   * MaxLength field in *Input → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.maxlength
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  maxlength: prismicT.NumberField;
  /**
   * MaxLengthValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.maxlengthvalidationmessage
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  maxlengthvalidationmessage: prismicT.KeyTextField;
}
/**
 * TextArea variation for Input Slice
 *
 * - **API ID**: `textArea`
 * - **Description**: `TextInput`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextInputSliceTextArea = prismicT.SharedSliceVariation<
  "textArea",
  Simplify<TextInputSliceTextAreaPrimary>,
  never
>;
/**
 * Primary content in Input → Primary
 *
 */
interface TextInputSliceEmailPrimary {
  /**
   * Name field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Label field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField;
  /**
   * Placeholder field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  placeholder: prismicT.KeyTextField;
  /**
   * Required field in *Input → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_input.primary.required
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  required: prismicT.BooleanField;
  /**
   * RequiredValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.requiredvalidationmessage
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  requiredvalidationmessage: prismicT.KeyTextField;
  /**
   * EmailValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.emailvalidationmessage
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  emailvalidationmessage: prismicT.KeyTextField;
}
/**
 * Email variation for Input Slice
 *
 * - **API ID**: `email`
 * - **Description**: `TextInput`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextInputSliceEmail = prismicT.SharedSliceVariation<
  "email",
  Simplify<TextInputSliceEmailPrimary>,
  never
>;
/**
 * Slice variation for *Input*
 *
 */
type TextInputSliceVariation =
  | TextInputSliceDefault
  | TextInputSliceTextArea
  | TextInputSliceEmail;
/**
 * Input Shared Slice
 *
 * - **API ID**: `text_input`
 * - **Description**: `TextInput`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextInputSlice = prismicT.SharedSlice<
  "text_input",
  TextInputSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AboutDocumentDataSlices1Slice,
      AboutDocument,
      BlogDocumentData,
      BlogDocument,
      BlogpostDocumentData,
      BlogpostDocumentDataSlicesSlice,
      BlogpostDocument,
      ContactDocumentData,
      ContactDocument,
      CookiebarDocumentData,
      CookiebarDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      FooterDocument,
      FormDocumentData,
      FormDocumentDataSlicesSlice,
      FormDocument,
      FormgroupDocumentData,
      FormgroupDocumentDataSlicesSlice,
      FormgroupDocument,
      HeaderDocumentData,
      HeaderDocument,
      HomePageArticleDocumentData,
      HomePageArticleDocumentDataSlicesSlice,
      HomePageArticleDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HomepageDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      NavigationDocument,
      AllDocumentTypes,
      BlogPostContentSliceDefaultItem,
      BlogPostContentSliceDefault,
      BlogPostContentSliceVariation,
      BlogPostContentSlice,
      FragmentSliceDefaultPrimary,
      FragmentSliceDefaultItem,
      FragmentSliceDefault,
      FragmentSliceHomepageFragmentPrimary,
      FragmentSliceHomepageFragmentItem,
      FragmentSliceHomepageFragment,
      FragmentSliceAboutMeFragmentPrimary,
      FragmentSliceAboutMeFragmentItem,
      FragmentSliceAboutMeFragment,
      FragmentSliceVariation,
      FragmentSlice,
      LinkButtonSliceDefaultPrimary,
      LinkButtonSliceDefault,
      LinkButtonSliceVariation,
      LinkButtonSlice,
      LinkIconSliceDefaultPrimary,
      LinkIconSliceDefault,
      LinkIconSliceVariation,
      LinkIconSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceDefault,
      NavigationItemSliceVariation,
      NavigationItemSlice,
      PlaceableContentSliceDefaultItem,
      PlaceableContentSliceDefault,
      PlaceableContentSliceVariation,
      PlaceableContentSlice,
      TextInputSliceDefaultPrimary,
      TextInputSliceDefault,
      TextInputSliceTextAreaPrimary,
      TextInputSliceTextArea,
      TextInputSliceEmailPrimary,
      TextInputSliceEmail,
      TextInputSliceVariation,
      TextInputSlice,
    };
  }
}
