// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = never;

type AboutDocumentDataSlices1Slice = FragmentSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Author field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_author: prismic.KeyTextField;

  /**
   * Meta Keywords field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Robots field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_robots: prismic.KeyTextField;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices1[]
   * - **Tab**: Page Content
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<AboutDocumentDataSlices1Slice>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Name field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.name
   * - **Tab**: Page Content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField
  /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Author field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_author: prismic.KeyTextField;

  /**
   * Meta Keywords field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Robots field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_robots: prismic.KeyTextField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type BlogpostDocumentDataSlicesSlice = BlogPostContentSlice | CodeBlockSlice;

/**
 * Content for BlogPost documents
 */
interface BlogpostDocumentData {
  /**
   * Name field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.name
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Header field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.header
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * DateCreated field in *BlogPost*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.datecreated
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  datecreated: prismic.TimestampField;

  /**
   * Background field in *BlogPost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.background
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<"medium" | "small">;

  /**
   * Thumbnail field in *BlogPost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.thumbnail
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Tags field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tags separated with semicolon
   * - **API ID Path**: blogpost.tags
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tags: prismic.KeyTextField;

  /**
   * Slice Zone field in *BlogPost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.slices[]
   * - **Tab**: Post Content
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice>
  /**
   * Meta Title field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Author field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_author: prismic.KeyTextField;

  /**
   * Meta Keywords field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Robots field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_robots: prismic.KeyTextField;
}

/**
 * BlogPost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Header field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.header
   * - **Tab**: Page Content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Subheading field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.subheading
   * - **Tab**: Page Content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField
  /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Author field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_author: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Keywords field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Robots field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_robots: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Content for CookieBar documents
 */
interface CookiebarDocumentData {
  /**
   * Name field in *CookieBar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookiebar.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * DeclineButtonText field in *CookieBar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookiebar.declinebuttontext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  declinebuttontext: prismic.KeyTextField;

  /**
   * AcceptButtonText field in *CookieBar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookiebar.acceptbuttontext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  acceptbuttontext: prismic.KeyTextField;

  /**
   * Content field in *CookieBar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookiebar.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * ExpirationTimeInDays field in *CookieBar*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cookiebar.expirationtimeindays
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  expirationtimeindays: prismic.NumberField;
}

/**
 * CookieBar document from Prismic
 *
 * - **API ID**: `cookiebar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CookiebarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CookiebarDocumentData>,
    "cookiebar",
    Lang
  >;

type FooterDocumentDataSlicesSlice = LinkIconSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Copy field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;

  /**
   * logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<"desktop">;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

type FormDocumentDataSlicesSlice = TextInputSlice;

/**
 * Content for Form documents
 */
interface FormDocumentData {
  /**
   * Name field in *Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * SubmitLabel field in *Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.submitlabel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submitlabel: prismic.KeyTextField;

  /**
   * Slice Zone field in *Form*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: form.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FormDocumentDataSlicesSlice>;
}

/**
 * Form document from Prismic
 *
 * - **API ID**: `form`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FormDocumentData>, "form", Lang>;

type FormgroupDocumentDataSlicesSlice = TextInputSlice;

/**
 * Content for FormGroup documents
 */
interface FormgroupDocumentData {
  /**
   * Name field in *FormGroup*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formgroup.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Slice Zone field in *FormGroup*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: formgroup.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FormgroupDocumentDataSlicesSlice>;
}

/**
 * FormGroup document from Prismic
 *
 * - **API ID**: `formgroup`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormgroupDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FormgroupDocumentData>,
    "formgroup",
    Lang
  >;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * header field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * subheader field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.subheader
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheader: prismic.KeyTextField;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;

type HomePageArticleDocumentDataSlicesSlice =
  | PlaceableContentSlice
  | LinkButtonSlice;

/**
 * Content for Home Page Article documents
 */
interface HomePageArticleDocumentData {
  /**
   * Name field in *Home Page Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_article.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Header field in *Home Page Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_article.header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Placement field in *Home Page Article*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_article.placement
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  placement: prismic.SelectField<"start" | "center" | "end">;

  /**
   * With Intersection field in *Home Page Article*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home_page_article.with_intersection
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  with_intersection: prismic.BooleanField;

  /**
   * Order field in *Home Page Article*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_article.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Slice Zone field in *Home Page Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageArticleDocumentDataSlicesSlice>;
}

/**
 * Home Page Article document from Prismic
 *
 * - **API ID**: `home_page_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomePageArticleDocumentData>,
    "home_page_article",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = FragmentSlice;

type HomepageDocumentDataSlices1Slice = SeoSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Page Content
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Author field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_author
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_author: prismic.KeyTextField;

  /**
   * Meta Keywords field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Robots field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_robots
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_robots: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices1[]
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<HomepageDocumentDataSlices1Slice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type NavigationDocumentDataSlicesSlice = NavigationItemSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Name field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * homePageUrl field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.homepageurl
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  homepageurl: prismic.LinkField;

  /**
   * homePageIcon field in *Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.homepageicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  homepageicon: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | BlogDocument
  | BlogpostDocument
  | ContactDocument
  | CookiebarDocument
  | FooterDocument
  | FormDocument
  | FormgroupDocument
  | HeaderDocument
  | HomePageArticleDocument
  | HomepageDocument
  | NavigationDocument;

/**
 * Primary content in *BlogPostContent → Items*
 */
export interface BlogPostContentSliceDefaultItem {
  /**
   * Content field in *BlogPostContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_content.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *BlogPostContent → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_content.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * ImageCaption field in *BlogPostContent → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_content.items[].imagecaption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  imagecaption: prismic.KeyTextField;
}

/**
 * Default variation for BlogPostContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: BlogPostContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<BlogPostContentSliceDefaultItem>
>;

/**
 * Primary content in *BlogPostContent → Items*
 */
export interface BlogPostContentSliceWithCodeBlockItem {
  /**
   * Content field in *BlogPostContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_content.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *BlogPostContent → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_content.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * ImageCaption field in *BlogPostContent → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_content.items[].imagecaption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  imagecaption: prismic.KeyTextField;

  /**
   * Language field in *BlogPostContent → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_content.items[].language
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  language: prismic.SelectField<
    | "bash"
    | "tsx"
    | "jsx"
    | "javascript"
    | "typescript"
    | "css"
    | "scss"
    | "json"
  >;

  /**
   * ShowLineNumbers field in *BlogPostContent → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_post_content.items[].showlinenumbers
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  showlinenumbers: prismic.BooleanField;

  /**
   * WrapLines field in *BlogPostContent → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_post_content.items[].wraplines
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  wraplines: prismic.BooleanField;

  /**
   * ShowCopyButton field in *BlogPostContent → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_post_content.items[].showcopybutton
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  showcopybutton: prismic.BooleanField;

  /**
   * Code field in *BlogPostContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_content.items[].code
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  code: prismic.RichTextField;
}

/**
 * With CodeBlock variation for BlogPostContent Slice
 *
 * - **API ID**: `withCodeBlock`
 * - **Description**: BlogPostContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostContentSliceWithCodeBlock = prismic.SharedSliceVariation<
  "withCodeBlock",
  Record<string, never>,
  Simplify<BlogPostContentSliceWithCodeBlockItem>
>;

/**
 * Slice variation for *BlogPostContent*
 */
type BlogPostContentSliceVariation =
  | BlogPostContentSliceDefault
  | BlogPostContentSliceWithCodeBlock;

/**
 * BlogPostContent Shared Slice
 *
 * - **API ID**: `blog_post_content`
 * - **Description**: BlogPostContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostContentSlice = prismic.SharedSlice<
  "blog_post_content",
  BlogPostContentSliceVariation
>;

/**
 * Primary content in *CodeBlock → Primary*
 */
export interface CodeBlockSliceDefaultPrimary {
  /**
   * Language field in *CodeBlock → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: code_block.primary.language
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  language: prismic.SelectField<
    | "tsx"
    | "typescript"
    | "jsx"
    | "javascript"
    | "css"
    | "scss"
    | "bash"
    | "json"
  >;

  /**
   * CodeString field in *CodeBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: code_block.primary.codestring
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  codestring: prismic.RichTextField;

  /**
   * ShowLineNumbers field in *CodeBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: code_block.primary.showlinenumbers
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  showlinenumbers: prismic.BooleanField;

  /**
   * WrapLines field in *CodeBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: code_block.primary.wraplines
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  wraplines: prismic.BooleanField;

  /**
   * ShowCopyButton field in *CodeBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: code_block.primary.showcopybutton
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  showcopybutton: prismic.BooleanField;
}

/**
 * Default variation for CodeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CodeBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CodeBlock*
 */
type CodeBlockSliceVariation = CodeBlockSliceDefault;

/**
 * CodeBlock Shared Slice
 *
 * - **API ID**: `code_block`
 * - **Description**: CodeBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeBlockSlice = prismic.SharedSlice<
  "code_block",
  CodeBlockSliceVariation
>;

/**
 * Primary content in *Fragment → Primary*
 */
export interface FragmentSliceDefaultPrimary {
  /**
   * Header field in *Fragment → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;
}

/**
 * Primary content in *Fragment → Items*
 */
export interface FragmentSliceDefaultItem {
  /**
   * Content field in *Fragment → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Fragment Slice
 *
 * - **API ID**: `default`
 * - **Description**: Fragment
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FragmentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FragmentSliceDefaultPrimary>,
  Simplify<FragmentSliceDefaultItem>
>;

/**
 * Primary content in *Fragment → Primary*
 */
export interface FragmentSliceHomepageFragmentPrimary {
  /**
   * Header field in *Fragment → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;

  /**
   * Placement field in *Fragment → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.primary.placement
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  placement: prismic.SelectField<"Left" | "Right">;

  /**
   * With Intersection field in *Fragment → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: fragment.primary.with_intersection
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  with_intersection: prismic.BooleanField;
}

/**
 * Primary content in *Fragment → Items*
 */
export interface FragmentSliceHomepageFragmentItem {
  /**
   * Content field in *Fragment → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button Link field in *Fragment → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Homepage Fragment variation for Fragment Slice
 *
 * - **API ID**: `homepageFragment`
 * - **Description**: Fragment
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FragmentSliceHomepageFragment = prismic.SharedSliceVariation<
  "homepageFragment",
  Simplify<FragmentSliceHomepageFragmentPrimary>,
  Simplify<FragmentSliceHomepageFragmentItem>
>;

/**
 * Primary content in *Fragment → Primary*
 */
export interface FragmentSliceAboutMeFragmentPrimary {
  /**
   * Header field in *Fragment → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;

  /**
   * Portrait field in *Fragment → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.primary.portrait
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portrait: prismic.ImageField<never>;
}

/**
 * Primary content in *Fragment → Items*
 */
export interface FragmentSliceAboutMeFragmentItem {
  /**
   * Content field in *Fragment → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fragment.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * About Me Fragment variation for Fragment Slice
 *
 * - **API ID**: `aboutMeFragment`
 * - **Description**: Fragment
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FragmentSliceAboutMeFragment = prismic.SharedSliceVariation<
  "aboutMeFragment",
  Simplify<FragmentSliceAboutMeFragmentPrimary>,
  Simplify<FragmentSliceAboutMeFragmentItem>
>;

/**
 * Slice variation for *Fragment*
 */
type FragmentSliceVariation =
  | FragmentSliceDefault
  | FragmentSliceHomepageFragment
  | FragmentSliceAboutMeFragment;

/**
 * Fragment Shared Slice
 *
 * - **API ID**: `fragment`
 * - **Description**: Fragment
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FragmentSlice = prismic.SharedSlice<
  "fragment",
  FragmentSliceVariation
>;

/**
 * Primary content in *LinkButton → Primary*
 */
export interface LinkButtonSliceDefaultPrimary {
  /**
   * Label field in *LinkButton → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_button.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Href field in *LinkButton → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_button.primary.href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField;

  /**
   * Placement field in *LinkButton → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: link_button.primary.placement
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  placement: prismic.SelectField<"start" | "center" | "end">;

  /**
   * Disabled field in *LinkButton → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: link_button.primary.disabled
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  disabled: prismic.BooleanField;
}

/**
 * Default variation for LinkButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: LinkButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkButton*
 */
type LinkButtonSliceVariation = LinkButtonSliceDefault;

/**
 * LinkButton Shared Slice
 *
 * - **API ID**: `link_button`
 * - **Description**: LinkButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkButtonSlice = prismic.SharedSlice<
  "link_button",
  LinkButtonSliceVariation
>;

/**
 * Primary content in *LinkIcon → Primary*
 */
export interface LinkIconSliceDefaultPrimary {
  /**
   * Href field in *LinkIcon → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_icon.primary.href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField;

  /**
   * Icon field in *LinkIcon → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: link_icon.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Default variation for LinkIcon Slice
 *
 * - **API ID**: `default`
 * - **Description**: LinkIcon
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkIconSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkIconSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkIcon*
 */
type LinkIconSliceVariation = LinkIconSliceDefault;

/**
 * LinkIcon Shared Slice
 *
 * - **API ID**: `link_icon`
 * - **Description**: LinkIcon
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkIconSlice = prismic.SharedSlice<
  "link_icon",
  LinkIconSliceVariation
>;

/**
 * Primary content in *NavigationItem → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
  /**
   * Name field in *NavigationItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: navigation_item.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Link field in *NavigationItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;

/**
 * Primary content in *PlaceableContent → Items*
 */
export interface PlaceableContentSliceDefaultItem {
  /**
   * Content field in *PlaceableContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: placeable_content.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Content Placement field in *PlaceableContent → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: placeable_content.items[].content_placement
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_placement: prismic.SelectField<"start" | "center" | "end">;

  /**
   * Button Link Href field in *PlaceableContent → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: placeable_content.items[].button_link_href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_href: prismic.LinkField;

  /**
   * Button Link Label field in *PlaceableContent → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: placeable_content.items[].button_link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_link_label: prismic.KeyTextField;

  /**
   * Button Link Placement field in *PlaceableContent → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: placeable_content.items[].button_link_placement
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_link_placement: prismic.SelectField<"start" | "center" | "end">;
}

/**
 * Default variation for PlaceableContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: PlaceableContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlaceableContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<PlaceableContentSliceDefaultItem>
>;

/**
 * Slice variation for *PlaceableContent*
 */
type PlaceableContentSliceVariation = PlaceableContentSliceDefault;

/**
 * PlaceableContent Shared Slice
 *
 * - **API ID**: `placeable_content`
 * - **Description**: PlaceableContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlaceableContentSlice = prismic.SharedSlice<
  "placeable_content",
  PlaceableContentSliceVariation
>;

/**
 * Primary content in *Seo → Primary*
 */
export interface SeoSliceDefaultPrimary {
  /**
   * meta_title field in *Seo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * meta_description field in *Seo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.primary.meta_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * meta_author field in *Seo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.primary.meta_author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_author: prismic.KeyTextField;

  /**
   * meta_keywords field in *Seo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.primary.meta_keywords
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * meta_robots field in *Seo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.primary.meta_robots
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_robots: prismic.KeyTextField;

  /**
   * meta_og_type field in *Seo → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: website
   * - **API ID Path**: seo.primary.meta_og_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  meta_og_type: prismic.SelectField<"website" | "article", "filled">;

  /**
   * meta_og_title field in *Seo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.primary.meta_og_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_title: prismic.KeyTextField;

  /**
   * meta_og_image field in *Seo → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.primary.meta_og_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_og_image: prismic.ImageField<never>;

  /**
   * meta_og_url field in *Seo → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.primary.meta_og_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  meta_og_url: prismic.LinkField;

  /**
   * meta_og_site_name field in *Seo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: fderenowski.dev
   * - **API ID Path**: seo.primary.meta_og_site_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_site_name: prismic.KeyTextField;

  /**
   * meta_og_description field in *Seo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.primary.meta_og_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  meta_og_description: prismic.RichTextField;
}

/**
 * Default variation for Seo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SeoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Seo*
 */
type SeoSliceVariation = SeoSliceDefault;

/**
 * Seo Shared Slice
 *
 * - **API ID**: `seo`
 * - **Description**: Seo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeoSlice = prismic.SharedSlice<"seo", SeoSliceVariation>;

/**
 * Primary content in *Input → Primary*
 */
export interface TextInputSliceDefaultPrimary {
  /**
   * Name field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Label field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Placeholder field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Required field in *Input → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_input.primary.required
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  required: prismic.BooleanField;

  /**
   * RequiredValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.requiredvalidationmessage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  requiredvalidationmessage: prismic.KeyTextField;

  /**
   * MinLength field in *Input → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.minlength
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  minlength: prismic.NumberField;

  /**
   * MinLengthValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.minlengthvalidationmessage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  minlengthvalidationmessage: prismic.KeyTextField;

  /**
   * MaxLength field in *Input → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.maxlength
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  maxlength: prismic.NumberField;

  /**
   * MaxLengthValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.maxlengthvalidationmessage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  maxlengthvalidationmessage: prismic.KeyTextField;
}

/**
 * Default variation for Input Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextInput
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextInputSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextInputSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Input → Primary*
 */
export interface TextInputSliceTextAreaPrimary {
  /**
   * Name field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Label field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Placeholder field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Required field in *Input → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_input.primary.required
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  required: prismic.BooleanField;

  /**
   * RequiredValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.requiredvalidationmessage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  requiredvalidationmessage: prismic.KeyTextField;

  /**
   * MinLength field in *Input → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.minlength
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  minlength: prismic.NumberField;

  /**
   * MinLengthValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.minlengthvalidationmessage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  minlengthvalidationmessage: prismic.KeyTextField;

  /**
   * MaxLength field in *Input → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.maxlength
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  maxlength: prismic.NumberField;

  /**
   * MaxLengthValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.maxlengthvalidationmessage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  maxlengthvalidationmessage: prismic.KeyTextField;
}

/**
 * TextArea variation for Input Slice
 *
 * - **API ID**: `textArea`
 * - **Description**: TextInput
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextInputSliceTextArea = prismic.SharedSliceVariation<
  "textArea",
  Simplify<TextInputSliceTextAreaPrimary>,
  never
>;

/**
 * Primary content in *Input → Primary*
 */
export interface TextInputSliceEmailPrimary {
  /**
   * Name field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Label field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Placeholder field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Required field in *Input → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_input.primary.required
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  required: prismic.BooleanField;

  /**
   * RequiredValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.requiredvalidationmessage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  requiredvalidationmessage: prismic.KeyTextField;

  /**
   * EmailValidationMessage field in *Input → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_input.primary.emailvalidationmessage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  emailvalidationmessage: prismic.KeyTextField;
}

/**
 * Email variation for Input Slice
 *
 * - **API ID**: `email`
 * - **Description**: TextInput
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextInputSliceEmail = prismic.SharedSliceVariation<
  "email",
  Simplify<TextInputSliceEmailPrimary>,
  never
>;

/**
 * Slice variation for *Input*
 */
type TextInputSliceVariation =
  | TextInputSliceDefault
  | TextInputSliceTextArea
  | TextInputSliceEmail;

/**
 * Input Shared Slice
 *
 * - **API ID**: `text_input`
 * - **Description**: TextInput
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextInputSlice = prismic.SharedSlice<
  "text_input",
  TextInputSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AboutDocumentDataSlices1Slice,
      BlogDocument,
      BlogDocumentData,
      BlogpostDocument,
      BlogpostDocumentData,
      BlogpostDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      CookiebarDocument,
      CookiebarDocumentData,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      FormDocument,
      FormDocumentData,
      FormDocumentDataSlicesSlice,
      FormgroupDocument,
      FormgroupDocumentData,
      FormgroupDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HomePageArticleDocument,
      HomePageArticleDocumentData,
      HomePageArticleDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HomepageDocumentDataSlices1Slice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogPostContentSlice,
      BlogPostContentSliceDefaultItem,
      BlogPostContentSliceWithCodeBlockItem,
      BlogPostContentSliceVariation,
      BlogPostContentSliceDefault,
      BlogPostContentSliceWithCodeBlock,
      CodeBlockSlice,
      CodeBlockSliceDefaultPrimary,
      CodeBlockSliceVariation,
      CodeBlockSliceDefault,
      FragmentSlice,
      FragmentSliceDefaultPrimary,
      FragmentSliceDefaultItem,
      FragmentSliceHomepageFragmentPrimary,
      FragmentSliceHomepageFragmentItem,
      FragmentSliceAboutMeFragmentPrimary,
      FragmentSliceAboutMeFragmentItem,
      FragmentSliceVariation,
      FragmentSliceDefault,
      FragmentSliceHomepageFragment,
      FragmentSliceAboutMeFragment,
      LinkButtonSlice,
      LinkButtonSliceDefaultPrimary,
      LinkButtonSliceVariation,
      LinkButtonSliceDefault,
      LinkIconSlice,
      LinkIconSliceDefaultPrimary,
      LinkIconSliceVariation,
      LinkIconSliceDefault,
      NavigationItemSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceVariation,
      NavigationItemSliceDefault,
      PlaceableContentSlice,
      PlaceableContentSliceDefaultItem,
      PlaceableContentSliceVariation,
      PlaceableContentSliceDefault,
      SeoSlice,
      SeoSliceDefaultPrimary,
      SeoSliceVariation,
      SeoSliceDefault,
      TextInputSlice,
      TextInputSliceDefaultPrimary,
      TextInputSliceTextAreaPrimary,
      TextInputSliceEmailPrimary,
      TextInputSliceVariation,
      TextInputSliceDefault,
      TextInputSliceTextArea,
      TextInputSliceEmail,
    };
  }
}
