// Code generated by Slice Machine. DO NOT EDIT.

import Fragment from './Fragment';
import Input from './Input';
import LinkButton from './LinkButton';
import LinkIcon from './LinkIcon';
import NavigationItem from './NavigationItem';
import PlaceableContent from './PlaceableContent';

export {
	Fragment,
	Input,
	LinkButton,
	LinkIcon,
	NavigationItem,
	PlaceableContent,
};

export const components = {
	fragment: Fragment,
	text_input: Input,
	link_button: LinkButton,
	link_icon: LinkIcon,
	navigation_item: NavigationItem,
	placeable_content: PlaceableContent,
};
