// Code generated by Slice Machine. DO NOT EDIT.

import Header from './Header';
import Section from './Section';

export {
	Header,
	Section,
};

export const components = {
	header: Header,
	section: Section,
};
