// Code generated by Slice Machine. DO NOT EDIT.

import Fragment from './Fragment';
import Input from './Input';
import NavigationItem from './NavigationItem';

export {
	Fragment,
	Input,
	NavigationItem,
};

export const components = {
	fragment: Fragment,
	text_input: Input,
	navigation_item: NavigationItem,
};
